export enum LoadingTypesEnum {
  EMPTY = 'EMPTY',
  SPINNER = 'SPINNER',
  BAR = 'BAR',
  SKELETON = 'SKELETON',
  GAME = 'GAME',
  SKELETON_SPINNER = 'SKELETON_SPINNER',
  SKELETON_BAR = 'SKELETON_BAR',
}
